name: Windows RDP via Tailscale (B)

on:
  workflow_run:
    workflows: ["Windows RDP via Tailscale (A)"]
    types: [completed]

permissions:
  contents: read
  actions: write

jobs:
  rdp:
    runs-on: windows-2022
    timeout-minutes: 370
    steps:
      - name: 🧾 Read payload
        id: cfg
        shell: pwsh
        run: |
          $ev = ConvertFrom-Json '${{ toJson(github.event) }}'
          $p  = $ev.client_payload
          $tailnet = $p.ts_tailnet
          $apikey  = $p.ts_api_key
          $authkey = $p.ts_authkey
          $test    = [bool]$p.test_mode
          $runtime = if ($test) { 5 } else { 355 }
          "tailnet=$tailnet" | Out-File -Append $env:GITHUB_OUTPUT
          "apikey=$apikey"   | Out-File -Append $env:GITHUB_OUTPUT
          "authkey=$authkey" | Out-File -Append $env:GITHUB_OUTPUT
          "runtime=$runtime" | Out-File -Append $env:GITHUB_OUTPUT

      - name: ⚡ Install Tailscale
        shell: pwsh
        run: |
          $exe = "C:\Program Files\Tailscale\tailscale.exe"
          if (-not (Test-Path $exe)) {
            $url = 'https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe'
            $dst = "$env:TEMP\tailscale-setup.exe"
            Invoke-WebRequest -Uri $url -OutFile $dst -UseBasicParsing
            Start-Process -FilePath $dst -ArgumentList "/quiet" -Wait
          }
          Start-Service Tailscale -ErrorAction SilentlyContinue
          & $exe version

      - name: 🔐 Enable RDP user + firewall
        shell: pwsh
        run: |
          $u = "Bullettemporary"; $p = "Bullet@12345"
          $sec = ConvertTo-SecureString $p -AsPlainText -Force
          if (-not (Get-LocalUser -Name $u -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name $u -Password $sec -AccountNeverExpires
            Add-LocalGroupMember -Group Administrators -Member $u
            Add-LocalGroupMember -Group "Remote Desktop Users" -Member $u
          } else {
            Set-LocalUser -Name $u -Password $sec -AccountNeverExpires
            Enable-LocalUser -Name $u
          }
          Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: 🧹 Purge bullet* devices
        shell: pwsh
        run: |
          $hdr = @{ Authorization = "Bearer ${{ steps.cfg.outputs.apikey }}" }
          $tn  = [uri]::EscapeDataString("${{ steps.cfg.outputs.tailnet }}")
          try {
            $resp = Invoke-RestMethod -Method GET -Headers $hdr -Uri "https://api.tailscale.com/api/v2/tailnet/$tn/devices"
            foreach ($d in $resp.devices) {
              if ($d.name -match '^(?i)bullet') {
                try { Invoke-RestMethod -Method DELETE -Headers $hdr -Uri "https://api.tailscale.com/api/v2/device/$($d.id)" }
                catch { Write-Warning "Skip delete $($d.name)" }
              }
            }
          } catch { Write-Warning "Purge failed: $_" }

      - name: 🔗 Tailscale up
        shell: pwsh
        run: |
          $ts = "C:\Program Files\Tailscale\tailscale.exe"
          & $ts logout | Out-Null
          & $ts up --authkey "${{ steps.cfg.outputs.authkey }}" --hostname bullet --accept-routes --accept-dns=false
          $ip4 = & $ts ip -4 | Select-Object -First 1
          $status = & $ts status --json | ConvertFrom-Json
          $fqdn = $status.Self.DNSName
          "### RDP CONNECT (B)`nHost: bullet`nIPv4: $ip4`nDNS: $fqdn`nUser: Bullettemporary`nPass: Bullet@12345" | Out-File $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
